apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: impromptu-ai
  labels:
    app.kubernetes.io/name: ai-service
    app.kubernetes.io/part-of: impromptu-ai
spec:
  # Internal communication only
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ai-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
